### ISSUE TITLE
no mongodb drivers installed, no mongodb yet created

### ISSUE THREAD

**Issue by dviramontes** [dviramontes/impress#1]
install mongodb,
install mongodb via npm with --save flag to update package.json,
create db instance,
populate db with user info,
read and write to db instance.

**Comment by jgillham** [comment]
That's reasonable first goal. I am sorry I didn't give you feedback earlier.

**Comment by jgillham** [comment]
I have already setup MongoDB on my computer if this what you are trying to do.  Go to [the website](http://www.mongodb.org/downloads) and download a package according to your operating system.
<pre><code>
cd /opt
tar zxf <file>
cd mongo*/bin
sudo mongod &
</code><pre>
