### ISSUE TITLE
Install Mocha Test runner

### ISSUE THREAD

**Issue by jgillham** [dviramontes/impress#3]
- [ ] 1. Install and save the developer dependency for mocha.
  <pre><code>
  npm install mocha --save-dev
  </code></pre>

**Comment by dviramontes** [comment]
yes, exactly. Do we do the same for mongodb ? install it as a development dependency? Lets talk about this. There are options for diff scenerios.

**Comment by jgillham** [comment]
The MongoDB that I use is the actual binary. Checkout my [other post](https://github.com/dviramontes/impress/issues/1) for how to install. I use mongojs which provides the API to talk to database. Installed like this:

<pre><code>
npm install mongojs --save
</code></pre>

 I was looking into a MongoDB that runs purely on JS. I haven't explored much further than that but it could be an interesting alternative.
