### ISSUE TITLE
Helpful README.md

### ISSUE THREAD

**Issue by jgillham** [dviramontes/impress#4]
- [x] README.md should contain description section.
- [x] README.md should contain table of contents section.
- [x] README.md should contain system requirements section.
- [x] README.md should use explain why the project was created.
- [x] README.md should use explain who created the project.
- [x] README.md should use explain the purpose of the project.
- [x] README.md should use explain how consumers can set the project up.
- [x] README.md should use explain how developers can set the project up.
- [x] README.md should use explain what are the features of the project.
- [x] README.md should use explain how to become a developer.
- [x] README.md should use explaining testing.
- [x] README.md should contain helpful information to get any future developers started.
- [x] README.md should use [GitHub Flavored Markdown](http://github.github.com/github-flavored-markdown/)

**Comment by dviramontes** [comment]
Excellent.
